version: '3.9'

services:
  webapp:
    build:
      context: ./WebApp
    ports:
      - "8080:80"
    networks:
      - app-network

  adminapp:
    build:
      context: ./AdminApp
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
